dist: trusty
sudo: required
language: python
python:
- '2.7'
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
env:
  global:
  - secure: N6yYHQvzkcL9qeyAphzNpFvD/djP87FRQfz+QFVmUnQUmYgJqq+iLaYYDu+LR6yslu/9vz2HvQAEoxq1VfwCC5TjR3Lsnh5u5rl6pncnvIhQYTSZuiUkp+SZe/pdkVejnHXuDC9oihhEqYw2O6YrT5Zj5kL1/ql7e3c7Gk0OmjI=
  - secure: BhwV+I76DmyW6wC/xFmiwV3R6L6SaEzm664d7kSvZiTYdJqPH+I912tmFc9javwUXrrZrYtyAqkUOvbRmEgYNEOERIWpdYFLZRupoZ4ankhEsIjjKBNQ/UoczNjHoMtuingkHErUK4xVRyZ0CN2fy8mPVkkTaqksdCzFHkz/XQ4=
  - secure: Hw5hR/zNzTm/B3ebNGtjyRwpj7uTRzlR6xZ17rBcxlStjgk8SVfXGpXtRrAHQEcEwani8jWgBo/hYdJevFVPFLuOQL41IpRnRYpnmXpDYlvQeXhgJv1j3/EkHoeyreMdgEMXg2ufhJUGIwzXywG5wofqXgZRpyJCzesRiSj7yBo=
  - secure: edh2vIa1saOTO+D+JJet3w85WFSAbsosM8iuSxeSZlVIQyw8S8q8KR1VA1tTT0hmHmRQ9OYndcSIGjZv3/0eKdw1p+r6Xf5EXsbVyesLoxSl95Xdi/9Xl0w+2Z0PTTjoywm6q5F+mWApOrdmZp+9jXBwhygmEHB8y7hG0BA9X7g=
  - secure: aM7aKpnL6JDgRpsNBxHDP8hrQat8E/swbSojNXoFp9M6oEZuH8ax7QcC53bLRHeXvhiHZAmVgoaw2X3ipD4JSlC9P3MQjl5Cm/oSczTpGYm/1+1i+L11gFfXSzaodbRDHO9rLHTF5igWksYQd+pQRpz28JIOgMXJ0djH/XebgfM=
  - secure: TV3eengGknJ24hSa3Ez5fTvgK+XTlOomJbggUwZeXfpRqoA8khfLb5KVCkgNQoofVwdQigW8FFIEkxadgfGFC7CPunW8BqnKlHAjtKJvvxSGjTU9G7YvsnNx0DP9JfSVmB7GCD/UsTwASGi0IZAAO9vQkPBVLSLmVQuJPlkyhgE=
  - secure: DzrQ6IHMEKnCtnLz2jfHjcAnylO82NR7lPDIVGu1v62k5PCmvoH3JLYugvyKHaWevB+yCP2NqJ79BYaeG44icDKJ89/WkBU+zuV3TibJpFtGGgdF8NlgbPbf7Xui1+tckbv7ieAmQ/zwKzvj2tnfOVIAUxr6OtzWK/AU9L/Z184=
  - secure: lg2/eseAVM+SYirOVWIB0AFIZxnM97q6iVH3uzXmmhOpdjfGq5cvo8AjC/aWQGGDGmIxk3jxvBHVaIYlAnMUmHsaNFDWEDunX20LKofN3y5sbw4UpoUnCS4xqoOYz8wJFEyWKkEkOOOmswtHW9/G4tgYN/zOjtyZ6j1bLvQEPWg=
  - secure: Djcr3UhZ0iqVTmSW3D76XzSEzdZEMHKUh/S/xragtgDD7Q9iw4i3DxDjdOuNirSdN5QcRnC0EKH+yKmEKP/2e8s5PO6BhoIwy9bZBoWSoo1amXRueHX2NiJKW9b1uNGABB8ZwtU6RBbNMxPYrPKcoHhaBgTPq9BICLwnzEOLuhw=
  - secure: A4SXbcIxRvXrPArNuu+h/1bUgE9UJ2nv4aPjdpboa+hViX5neFzBUYX6Y02yNVQs5049Hi20KlsEvcAceY5KCm5kPD6TmsOcWv3daRCO2jtuTmUPsOKMRMiaHD/hlSJunG1INJO/Mj1rWpW1V6fIoxZH35Du3UFmUkkuECRuz6E=
  - secure: a6y7u4zAaDdBp+5AMbogrlUNtxKdxA7/YCvel+blDL5VZyhZgLKlka6G+jE4zbRBpCtDacHJKWS1qtn4S5+tangWBNG01BZIacVKtn6Rhf1T6CnA5keZAISkNpt6C0Q0Z0fKqTbVDerQXLq/jtgsEudc8tIGu3IY7bVLpzx0SSk=
  - secure: fkn6QxylsJrVNZg+bsqRGaQBT7usqd/9wyuVM8HRBOj5JU/qBodMsCV9spe2LweccSAC9mH35mLKaXIVFTQx54DANtoWZZuiVr4qrrkenxGsWHyCKo7rEmFa5RjIOrRCCipHN0j3fs8NM0SKZS5Qwup78ERGO92N5IAB2Y6Efbg=
  - secure: oM5Jm5KUtfT9DqnbRiswBZYe1LcCbtI+z3h4hBpsZqFWooj+xjMWLJLBW8ED4g1n0JImqQUyoxfHmh07Qj6Ctp71RX2rfe7sttm0e1zV26df9lLDhTZPWGkEhq2qevS9YWrhbJPTqRkAb4KOGfz1LYqDpp9pa1yKrr5NaKc+tYU=
  - secure: GtVRt7QpgMPAt5yPLjHtCoF62CJ2QGk6JC3KFsS780INo1/VP7XgGqqkzRKpa0Yt2fWSAXO1i6N5sztPDOe9Tk2r1zvsBTG6J41O7v6e4ZmqkZmYSW0VuRRqGKO+Kik9Q/uo0TCpfGuYEkMDfm7kvt2QJyfJJFJ6mmv/NWHpNxA=
  - secure: ASswg5Qgc0QpV+3NNM4aym9MnpApMxdj7IDgMksRkeF4QAwyrSROKaLqJyPH126s58yiflIAiO3KKcBCI3pBbCXdSCEBJcm84UsHrQA6TmHNoUQDhhtWQ/NB6DZq1/FihbOx6FE3jfccGdauz2nmktkLq+hUJxm+I8drFGgTNS4=
  - secure: Vru1IVryYnz4lrwWE5njOwENmTyegAcC4QNlpl8n9OI7sZR0mHDF7ynzekpKt/3r7h3GMnKNuYQzF/YYrOsfZEIp6ODSL9UUKpOFTsN91bol+FZRPzcCmDFcNkJujLGD8u10jsJOly9Wkr9/1ZOjYMKFYtIZxLfkqJmG6xhpGzY=
  - secure: jJcK7tRNzUK2PQuWCoATUNFXIHttTXLIhL25CwKYJLQUlsvidPpnDB7Mf53YCfUL06c7ocqbdAM2Tl5te+28Tgzlg5wbK0E4I/hSKnOqpPDp6eLRIcGh2uAgZFoLUgeaylMeAexLknRiBmZRNNKT8SFxq412T+t41WbXm0IftWM=
  - secure: FZmSXnv4pQ7iZ1r0ttjFEogNX6FQTKcXWKgK0aXgDR5DMvsw+GuL1q+anukTzWDEdWGhkQeumCkey8dRHl2bE2iUknnknTnlOcNFhPBLQbfqv0nYtGeauJkjEkeN4CAPuUTDwmIpIGIJS4LSDWm2lQTO+tX2CwJuX5IAND51uV0=
  - secure: gRAAJ/4TyZoXSW+/R8bnc+u5/LG5uY0lx/pT/MAF7j+3fgZNoFf3znwNPe02DmTg4YfshUR2/F1dgXEEMI8pNkPvpA9aI8EHYBJ47Kq8Xl9WoCo4wPCLeeeqUNhkus8JwGwEYgRHaP2vjJX45Vj0+MLOB7vj1Xjphey8BZ/FTIg=
  - secure: hxWLkmCdWBIH0NkA0qZhn5oJKiaCnSFZjezLAEa0krX5tCrV63eVzJAXgcN0sznQKr2YjzQ7qCBIrCQSLyAPM7WrEVSKLt9m9F9X290U6T0NUuDZ5n7kpO0qRV8rUguraZIj0JeBk8+S3QiiNg/gAmrcYtnY8mPhFsUDfII7qj0=
  - secure: gxuUzleY30Xef4YaG1QhhiE6LFQDAVulrjfLzGa2Ou20wv6peMlTq9fB8JkbfzzUVGqU+iABk+rnZU6yHrWMiGl6wv+3OIGjw28tadxCA066oHzajUF5qpIGPScP1c7r77oSu0UDUd/6qEXfeRWBI9udUIhpwIfxAHh1RoGlNoU=
  - secure: R39z4E6cdcoX8FwbLzlb6qt7Sc/GwqMXd6x1JGOHXxS5dLED7B37UJocBtOSzBLIs5eUmXa9FfT335XkOFCuk4iG6t4X78yMvGP6FRUJ+LRnej5s66lEdcGUnPMvBZt4lFVEPatYz1iFDbXcSUZImAG8zYdEYDfJfWUgZX7S1vw=
  - secure: D34JJbIXtCSpwekw2msBMupRG1Q02CvieUOlmtU91wlESxE5/lR8iShGAg+1gQp+Po9tJE8earBT70/fxgli4tjzn5XPWvea4Kj2VnOJWmBgrlVmO88rkydFG+AcvT5pbHzRpT6W7mf1vnrDpDT4KCf+6Cb36fyynvhZpDTXQvo=
  matrix:
  - CONCURRENT_EVENTLET=0
  - CONCURRENT_EVENTLET=1
install: pip install .
script: nosetests
before_script: ".travis/before_script.sh"
deploy:
  provider: script
  script: ".travis/publish.sh"
  on:
    branch: staging
